BEGIN; 

DROP TABLE IF EXISTS "account" CASCADE;

CREATE TABLE "account" (
  "id" INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  "email" VARCHAR(350) NOT NULL,
  "prenom" VARCHAR(50) NOT NULL,
  "nom" VARCHAR(50) NOT NULL,
  "hash" TEXT NOT NULL
);

DROP TABLE IF EXISTS "favori" CASCADE;

CREATE TABLE "favori" (
  "id" INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  "titre" VARCHAR(42) NOT NULL,
  "lien" TEXT NOT NULL,
  "id_favori" INTEGER REFERENCES "account"("id")

);

DROP TABLE IF EXISTS "rdv" CASCADE;

CREATE TABLE "rdv" (
  "id" INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY , 
  "nom" VARCHAR(50) NOT NULL,
  "lieu" VARCHAR(60) NOT NULL,
  "date" date NOT NULL,
  "heure" time NOT NULL,
  "id_rdv" INTEGER REFERENCES "account"("id")

);

DROP TABLE IF EXISTS "note" CASCADE;

CREATE TABLE "note" (
  "id" INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY , 
  "note" TEXT NOT NULL,
  "id_note" INTEGER REFERENCES "account"("id")

);



COMMIT;