BEGIN; 

DROP TABLE IF EXISTS "note";

CREATE TABLE "note" (
  "id" INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  "description" TEXT NOT NULL
  
);

DROP TABLE IF EXISTS "rdv";

CREATE TABLE "rdv" (
  "id" INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  "nom" VARCHAR(42) NOT NULL,
  "lieu" VARCHAR(42) NOT NULL,
  "date" DATE NOT NULL,
  "heure" TIME NOT NULL
  
);

COMMIT;
